<a href="https://colab.research.google.com/github/CGnal/agos-ai-course/blob/master/2_1_introduction_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==2.6.2

     |████████████████████████████████| 458.3 MB 2.3 kB/s 
     |████████████████████████████████| 462 kB 58.1 MB/s 
     |████████████████████████████████| 1.3 MB 58.8 MB/s 
     |████████████████████████████████| 5.6 MB 54.7 MB/s 
  Created wheel for clang: filename=clang-5.0-py3-none-any.whl size=30692 sha256=77345b10fedb58c3fc17f354fd391dede887c8e1da0dffcca351ff3a3f4ca325
  Stored in directory: /root/.cache/pip/wheels/98/91/04/971b4c587cf47ae952b108949b46926f426c02832d120a082a
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=68717 sha256=706619a8be7d898c74a5fa06b1f5dfc7239d6feb1d69a6d818428fd0dbed8e5e
  Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Successfully built clang wrapt
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.2
    Uninstalling typing-extensions-3.10.0.2:
      Successfully uninstalled typing-extensions-3.10.0.2
  Attemptin

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from keras.utils.vis_utils import plot_model
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np 
import pandas as pd 

In [ ]:
tf.__version__

'2.6.2'

# Tensors

A static numerical representation


1. Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.Dtype
2. Kind of like numpy.arrays()
3. All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.
4. Can be a **scalar, vector, 2 dimensional matrix or even an n-dimensional matrix**
5. Can be **floats of different kinds, Boolean, ints of all sorts, complex numbers, strings**





![picture](https://drive.google.com/uc?id=1eJlVeRhnNXWhB3kqXG4MWUK2GwE8BNPB)
![picture](https://drive.google.com/uc?id=1Pydas_Zw4Ddgbfz9GRan7TVpFyN1wpsh)
![picture](https://drive.google.com/uc?id=1NfllkuHE1jZXQEJr9R0SfTmxelN_hEqa)
![picture](https://drive.google.com/uc?id=1jW8srKRlMR5RDmz-iSzPKveF5nRMsL9R)
![picture](https://drive.google.com/uc?id=1ZIl-UAHgO7UYKOMPeu2ivRVCFqu5e_fa)



In [ ]:
#@title
%%html
<iframe src="https://drive.google.com/file/d/1eJlVeRhnNXWhB3kqXG4MWUK2GwE8BNPB/preview" width="200" height="200" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1Pydas_Zw4Ddgbfz9GRan7TVpFyN1wpsh/preview" width="200" height="200" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1NfllkuHE1jZXQEJr9R0SfTmxelN_hEqa/preview" width="200" height="200" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1jW8srKRlMR5RDmz-iSzPKveF5nRMsL9R/preview" width="200" height="200" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1ZIl-UAHgO7UYKOMPeu2ivRVCFqu5e_fa/preview" width="200" height="200" allow="autoplay"></iframe>


In [ ]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)


# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [ ]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
# we can easily use numpy operations on tensorflow tensors
np.array(rank_2_tensor)


array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

## Tensor can be complex numbers too

In [ ]:
complex_vec = tf.complex(real=1., imag=1.)
print(complex_vec)
tf.abs(complex_vec).numpy() # sqrt(1**2 + 1**2)


tf.Tensor((1+1j), shape=(), dtype=complex64)


1.4142135

## Basic Math Operations

In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")



print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


## Tensor attributes

1. **Shape**: The length (number of elements) of each of the axes of a tensor.
2. **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
3. **Axis or Dimension**: A particular dimension of a tensor.
4. **Size**: The total number of items in the tensor, the product shape vector.

More info :https://www.tensorflow.org/guide/tensor

![picture](https://drive.google.com/uc?id=1P389nGYZEPewQiECMdOk-huxxv99zMrw)
![picture](https://drive.google.com/uc?id=1ZMxJKjIK8CmdiHgQZbG27h-M3GSmAkDe)
![picture](https://drive.google.com/uc?id=1lXchHqo2HFSUy08EhC50PXB-FLqqvNim)


In [ ]:
#@title
%%html 
<iframe src="https://drive.google.com/file/d/1P389nGYZEPewQiECMdOk-huxxv99zMrw/preview" width="300" height="300" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1ZMxJKjIK8CmdiHgQZbG27h-M3GSmAkDe/preview" width="300" height="300" allow="autoplay"></iframe>
<iframe src="https://drive.google.com/file/d/1lXchHqo2HFSUy08EhC50PXB-FLqqvNim/preview" width="300" height="300" allow="autoplay"></iframe>

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())
print("Rank of tensor: ", tf.rank(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120
Rank of tensor:  4


# Variables

Where you store your changes

1. Variables are created and tracked via the tf.Variable class. 
2. A tf.Variable represents a tensor whose value can be changed by running ops on it. 
3. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like tf.keras use tf.Variable to store model parameters.

In [ ]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [ ]:
# variable uses a tensor behind
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


## Updating a Variable

1. Variables are backed by tensors. 
2. You can reassign the tensor using tf.Variable.assign. 
3. Calling assign does not (usually) allocate a new tensor; instead, the existing tensor's memory is reused.
4. cant reshape an existing tensor

In [ ]:
# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, [1,4]))



a = tf.Variable([2.0, 3.0])
print(a)
# This will keep the same dtype, float32
a.assign([1, 2]) 
print(a)

# Not allowed as it resizes the variable: 
try:
  a.assign([1.0, 2.0, 3.0])
except Exception as e:
  print(f"{type(e).__name__}: {e}")


Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
ValueError: Cannot assign to variable Variable:0 due to variable shape (2,) and value shape (3,) are incompatible


In [ ]:
# Creating new variables from existing variables duplicates the backing tensors.
# Two variables will not share the same memory.


a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]


#variables can be renamed too just pass the name parameter
tf.Variable([2.0, 3.0], name='myvar')

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


<tf.Variable 'myvar:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

## Placing variables and tensors

1. Directly place tensors and variables on a given device
2. Ofcourse gpu is faster than cpu if available



In [ ]:
tf.debugging.set_log_device_placement(True)

with tf.device('CPU:0'):

  # Create some tensors
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [ ]:
# runtime needs to be changed to GPU to place vars on gpu
tf.debugging.set_log_device_placement(True)
with tf.device('GPU:0'):

  # Create some tensors
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)

print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


# Automatic Differentiation
Calculus it is !

1. To do any kind of machine learning we need gradients
2. Gradients are very important especially in neural networks. 
3. We need gradients to do things like gradient descent




## Computing gradients in tensorflow : Gradient Tape

1. We want Tensorflow to calculate gradients for us automatically. 
2. Tensorflow does it in a smart way by building a computational graph and recording the list of operations and variables. 

3. **Forward mode** : TensorFlow needs to remember what operations happen in what order during the forward pass. 

4. **Reverse mode** : Then, during the backward pass, TensorFlow traverses this list of operations in reverse order to compute gradients.

![picture](https://drive.google.com/uc?id=1732JqqKcWbfSWw7Bd9zHXX_NffrPflN7)
![picture](https://drive.google.com/uc?id=1Sk7swUKnXPJscdCoO23Mh_tpmMLK4oOn)


In [ ]:
#@title
%%html
<iframe src="https://drive.google.com/file/d/1732JqqKcWbfSWw7Bd9zHXX_NffrPflN7/preview" width="650" height="200" allow="autoplay"></iframe>

<iframe src="https://drive.google.com/file/d/1Sk7swUKnXPJscdCoO23Mh_tpmMLK4oOn/preview" width="650" height="200" allow="autoplay"></iframe>

In [ ]:
x = tf.Variable(3.0)

# use a tape object to record all the operations on the given tensor
with tf.GradientTape() as tape:
  y = x**2


# dy = 2x * dx
dy_dx = tape.gradient(y, x)
dy_dx.numpy()



6.0

## Some calculus operations using Gradient Tape

x = \{x1, x2, x3, x4}

y = Σx

z = y**2

In [ ]:
x = tf.ones((2, 2))
  

# use a tape object to record all the operations on the given tensor
with tf.GradientTape() as t:
  t.watch(x) #ensures that the tensor is being traced
  y = tf.reduce_sum(x) #operation simply sum of elements of the tensor along an axis and outputs a scalar
  z = tf.multiply(y, y) #another tensor operation
  print(z)


# Derivative of z with respect to the original input tensor x
dz_dx = t.gradient(z, x)

# Since the input tensor is of shape 2,2 we expect the gradient to have 4 components i.e. 4 partial derivative components
print(dz_dx)
for i in [0, 1]:
  for j in [0, 1]:
    assert dz_dx[i][j].numpy() == 8.0

tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


## Get gradient of output with respect to intermediate values 
### **dz/dx** = **dz/dy**  **dy/dx** 

Remark : 
The tape object is destroyed once **tape.gradient** method is called. Use persistent=True to do further operations on the same tape object

In [ ]:
x = tf.constant(3.)
  

# persistent=True allows multiple operations on the same tape 

with tf.GradientTape(persistent=True) as t:
  t.watch(x) 
  y = x*x # y=x**2
  z = y*y # z=y*y=x**4


dz_dy = t.gradient(z, y)
print("2y:", dz_dy)

dy_dx = t.gradient(y, x)
print("2x:", dy_dx)

dz_dx = t.gradient(z, x)
print("4x**3:", dz_dx)

assert dz_dx.numpy()==dy_dx.numpy()*dz_dy.numpy()


2y: tf.Tensor(18.0, shape=(), dtype=float32)
2x: tf.Tensor(6.0, shape=(), dtype=float32)
4x**3: tf.Tensor(108.0, shape=(), dtype=float32)


## Gradients with respect to a model

Easy to calculate gradients with respect to a layer or a model's trainable variables 

In [ ]:
layer = tf.keras.layers.Dense(2, activation='relu')
x = tf.constant([[1., 2., 3.]])

with tf.GradientTape() as tape:
  # Forward pass
  y = layer(x)
  loss = tf.reduce_mean(y**2)

# Calculate gradients with respect to every trainable variable
grad = tape.gradient(loss, layer.trainable_variables)

In [ ]:
layer.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(3, 2) dtype=float32, numpy=
 array([[ 0.6094804 ,  0.48982775],
        [-0.9519953 , -1.0793213 ],
        [ 0.81474316,  0.1840086 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [ ]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1.1497194, 0.       ],
        [2.2994387, 0.       ],
        [3.4491582, 0.       ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1497194, 0.       ], dtype=float32)>]

In [ ]:
for var, g in zip(layer.trainable_variables, grad):
  print(f'{var.name}, shape: {g.shape}')


# gradients same shape as the variable 
# so thats how gradient tape lets us compute gradients with respect to any layer of our neural net

dense/kernel:0, shape: (3, 2)
dense/bias:0, shape: (2,)


## Some more things about Gradient Tape 

1. If else inside gradient tapes ? 
```python
x = tf.constant(1.0)
v0 = tf.Variable(2.0)
v1 = tf.Variable(2.0)
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x)
  if x > 0.0:
    result = v0
  else:
    result = v1**2 
dv0, dv1 = tape.gradient(result, [v0, v1])
print(dv0) #tf.Tensor(1.0, shape=(), dtype=float32)
print(dv1) #None
```

## Common errors
1. Replacing tf.Variable with a tf.Tensor
```python
x = tf.Variable(2.0)
for epoch in range(2):
  with tf.GradientTape() as tape:
    y = x+1
  print(type(x).__name__, ":", tape.gradient(y, x))
  x = x + 1   # This should be `x.assign_add(1)`
#ResourceVariable : tf.Tensor(1.0, shape=(), dtype=float32)
#EagerTensor : None
```

2. Calculations outside of TensorFlow
The tape can't record the gradient path if the calculation exits TensorFlow. For example:

```python
x = tf.Variable([[1.0, 2.0],
                 [3.0, 4.0]], dtype=tf.float32)

with tf.GradientTape() as tape:
  x2 = x**2

  # This step is calculated with NumPy
  y = np.mean(x2, axis=0)

  # Like most ops, reduce_mean will cast the NumPy array to a constant tensor
  # using `tf.convert_to_tensor`.
  y = tf.reduce_mean(y, axis=0)

print(tape.gradient(y, x))
# None
```

3. Typo when decalaring a tensor

```python
x = tf.constant(10)

with tf.GradientTape() as g:
  g.watch(x)
  y = x * x

print(g.gradient(y, x))
```

## Final thoughts on Gradient Tape

1. Tape stores all info regarding a trainable variable tf.Variable that it sees.

2. Records forward pass operations 
3. Calculates gradients in backward pass using recorded forward pass operations. 
4. Tape holds all intermediate outputs (we dont need to care actually) 
5. Most common use case: calculate gradient of a loss function with respect to all trainable vars of a model
6. In higher level APIs like Keras we don't need to explicity call gradient tape anywhere
7. But its pretty useful when building custom models

### tf.modules 
1. Helps to build models in tensorflow. 
2. All keras layers inherit from tf.modules
3. Any custom layer or model in tensorflow must inherit from this class.
4. But we will use tf.keras models to build our models


# Next steps ? 

1. We know some basic components of a graph
2. How do we build models ? 

### Now we can proceed on to keras to build some models 
